# Travis-CI configuration file for biodb extensions packages, version 1.1.2

language: r
cache: packages
r: release

env:
    - BIODB_USERAGENT="biodbLipidmaps.test ; pierrick.roger@cea.fr"

notifications:
    email:
        recipients:
            - pierrick.roger@cea.fr

branches:
  only:
    - master
    
before_install:
  - bash -c '[[ -f travis_deps.sh ]] && bash travis_deps.sh'
  - R -e 'install.packages("devtools")'
  - R -e 'devtools::install_github('pkrog/biodb', dependencies=TRUE)'
  - R -e 'install.packages("BiocManager");BiocManager::install("BiocCheck")'

script:
    - make check.all
